---
Name: silverstripetemplate-configconfig
---
Dynamic\TemplateConfig\Model\TemplateConfigSetting:
  extensions:
    - Dynamic\TemplateConfig\ORM\BrandingDataExtension
    - Dynamic\TemplateConfig\ORM\UtilityDataExtension
    - Dynamic\TemplateConfig\ORM\FooterDataExtension
    - Dynamic\TemplateConfig\ORM\SocialDataExtension
